[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Add your Sepolia private key here for deployment
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/w_dGzir944Ci5GJHm0rlZdexl1umMJVW"

[env]
PRIVATE_KEY = "529ff5679574b128d01f8afab91cb6110af53b2ec16234a15aafdef6c4756a8f"

remappings = [
  "fhevm-solidity/=lib/fhevm-solidity/",
  "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
